---
name: pre-commit Updater

on:
  schedule:
    - cron: "0 9 * * 1-5" # Monday-Friday at 09:00 UTC
  workflow_dispatch:

permissions: {}

jobs:
  pre-commit-updater:
    name: pre-commit Updater
    permissions:
      contents: write
      pull-requests: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/pre-commit-updater.yml@5ef7e57f1e9bf9f8cc865c6ed548708baaa75192 # v1.1.2
